### ISSUE TITLE
[Crash] App crashes in the currency converter

### ISSUE THREAD

**Issue by mxmvncnt** [prathameshmm02/Calculator-inator#35] opened 2022-07-19 02:45 UTC
The app crashes when selecting one of the two input fields of the currency converter section and inputting some data.

1. open the currency tab
2. select one of the two input fields
3. input something
4. select the other text field
5. attempt to input something, the app crashes here for me.

 I was able to reproduce this when starting from the first and the second text box, it has the same outcome.

Also, quick thing, some padding on the refresh button wouldn't hurt since it hides the bottom text field when the keyboard is up!

**Comment by DoozyDoz** [comment] 2022-09-13 08:04
Followed the steps, can't reproduce this

**Comment by prathameshmm02** [comment] 2023-03-10 12:23
Closing this as the bug can't be reproduced.

**Closed by prathameshmm02** 2023-03-10 12:23 UTC
